name: favorite_books
description: A HiveDB sample project that demonstrates simple use of HiveDB.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  hive: any
  hive_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
