name: sketchpad
description: A HiveDB sample project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter

  hive: any
  hive_flutter: any
  path_provider: any

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
